services:
  - type: web
    name: rentrite-ai-chat-api
    runtime: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: GOOGLE_API_KEY
        value: AIzaSyCnCxtKRmRxp9DOQcDi0htWHtj19mCJjpY