services:
  - type: web
    name: rentrite-ai-chat-api
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000
    envVars:
      - key: GOOGLE_API_KEY
        value: AIzaSyCnCxtKRmRxp9DOQcDi0htWHtj19mCJjpY
